### ISSUE TITLE
Adding a NeurIPS 2021 paper

### ISSUE THREAD

**Issue by korawat-tanwisuth** [zhaoxin94/awesome-domain-adaptation#101]
Thanks for creating this repository! It's a very comprehensive source of information.

Could you please add our NeurIPS 2021 paper, [a prototype-oriented framework for unsupervised domain adaptation](https://arxiv.org/abs/2110.12024)? The code is provided in this [link](https://github.com/korawat-tanwisuth/Proto_DA)?

We appreciate your help. Thanks!

**Comment by zhaoxin94** [comment]
Very impressive and interesting work! I have added it into the list.
