### ISSUE TITLE
Request to Add Paper

### ISSUE THREAD

**Issue by ldkong1205** [zhaoxin94/awesome-domain-adaptation#103]
Thank you for meticulously maintaining this repository!

Could you add our recent work on unsupervised domain adaptation (UDA) for LiDAR segmentation? We built the first benchmark for UDA in LiDAR segmentation (range-view) and tested other related DA cases with minimum supervisions, such as SSDA and WSDA. We also proposed a new algorithm that has achieved promising results.

- **Title:** ConDA: Unsupervised Domain Adaptation for LiDAR Segmentation via Regularized Domain Concatenation
- **Link**: https://arxiv.org/abs/2111.15242
- **Authors:** Lingdong Kong, Niamul Quader, Venice Erin Liong, Hanwang Zhang
- **Affiliations:** Nanyang Technological University, Motional (nuTonomy)
- **Tags:** `seg`, `uda`, `av`, `lidar`

**Comment by zhaoxin94** [comment]
Thanks for your appreciation.

Your work is really interesting and impressive. I have added it into the list.
