### ISSUE TITLE
Request to Add Paper

### ISSUE THREAD

**Issue by powerwen** [zhaoxin94/awesome-domain-adaptation#104]
Thank you for meticulously maintaining this repository!
I would like to suggest a new papers here.
Title: Probabilistic Contrastive Learning for Domain Adaptation
Link: https://arxiv.org/abs/2111.06021
Code: https://github.com/ljjcoder/Probabilistic-Contrastive-Learning 

In this paper, authors point out that feature contrastive learning is inferior to probabilistic contrastive learning in the domain adaptation task and demonstrate the effectiveness of probabilistic contrastive learning on multiple tasks (UDA, SSDA, SSL and UDA detection). 

Many thanks for your effort!

**Comment by zhaoxin94** [comment]
Thank you! I appreciate the compliment very much.

Your work is really impressive. I have added it into the paper list.

Best regards.
