### ISSUE TITLE
Request for adding paper

### ISSUE THREAD

**Issue by xiaoachen98** [zhaoxin94/awesome-domain-adaptation#110]
Thank you for maintaining this repository!
I would like to suggest a new conference paper belonging to Adversarial-based UDA (CVPR2022).
Title: Reusing the Task-specific Classifier as a Discriminator: Discriminator-free Adversarial Domain Adaptation
Link: https://arxiv.org/abs/2204.03838
Code: https://github.com/xiaoachen98/DALN

**Comment by zhaoxin94** [comment]
Thanks for your attention and your amazing work!
I have added it to the list.
