### ISSUE TITLE
Request to Add Paper

### ISSUE THREAD

**Issue by ldkong1205** [zhaoxin94/awesome-domain-adaptation#112]
Thank you for meticulously maintaining this repository!

We would like to recommend our recent work, TranSVAE, a disentanglement framework for unsupervised video domain adaptation, which has achieved SoTA performance among the UDA leaderboards of UCF-HMDB, Jester, and Epic-Kitchens.

- **Title:** Unsupervised Video Domain Adaptation: A Disentanglement Perspective
- **Paper:** https://arxiv.org/abs/2208.07365
- **Code:** https://github.com/ldkong1205/TranSVAE
- **Project Page:** https://ldkong.com/TranSVAE
- **Gradio Demo:** https://huggingface.co/spaces/ldkong/TranSVAE

Thanks again and best regards 🚀

**Comment by zhaoxin94** [comment]
Very solid and impressive work!
I have add it to the list!

**Comment by ldkong1205** [comment]
Thanks a lot!
