### ISSUE TITLE
Request for adding paper

### ISSUE THREAD

**Issue by xiaoachen98** [zhaoxin94/awesome-domain-adaptation#119]
Thank you for maintaining this repository!
I would like to suggest a new conference paper belonging to UDA Semantic Segmentation (NeurIPS2022).
Title: Deliberated Domain Bridging for Domain Adaptive Semantic Segmentation
Link: https://arxiv.org/abs/2209.07695
Code: https://github.com/xiaoachen98/DDB

**Comment by zhaoxin94** [comment]
Very impressive work! I have added it to the list.
