### ISSUE TITLE
Request to add a paper 

### ISSUE THREAD

**Issue by chi-chi-zx** [zhaoxin94/awesome-domain-adaptation#121]
Thank you for maintaining the paper lists!

We woulid like to request to add our NeurIPS2022 paper: "Meta-DMoE: Adapting to Domain Shift by Meta-Distillation from Mixture-of-Experts"

We utilize the multi-source paradigm and train multiple model experts for each of the source domian. At test-time, for each target domain, some unlabeled data are sampled to query the knowledge from the experts to distill the domain knowledge to a student network. The student network is then used for downstream inference. 

We think it might be suitable for multi-source DA, source-free DA, few-shot UDA or domain generalization.

Thank you!

**Comment by zhaoxin94** [comment]
Very impressive work! I have added it to the list.
