### ISSUE TITLE
Request to add three relevant papers

### ISSUE THREAD

**Issue by akshaykulkarni07** [zhaoxin94/awesome-domain-adaptation#123]
Hi, 
Thanks for your efforts in compiling and actively maintaining this list. Could you please add three of our recent works to this list:

Balancing Discriminability and Transferability for Source-Free Domain Adaptation [[ICML2022]](https://proceedings.mlr.press/v162/kundu22a.html) [[Project Page]](https://sites.google.com/view/mixup-sfda)

Concurrent Subsidiary Supervision for Unsupervised Source-Free Domain Adaptation [[ECCV2022]](https://www.ecva.net/papers/eccv_2022/papers_ECCV/html/912_ECCV_2022_paper.php) [[Project Page]](https://sites.google.com/view/sticker-sfda)

Subsidiary Prototype Alignment for Universal Domain Adaptation [[NeurIPS2022]](https://openreview.net/forum?id=5kThooa07pf) [[Project Page]](https://sites.google.com/view/spa-unida)

The first two can go in Source-Free DA section and third one in Universal DA.

Thanks again

**Comment by zhaoxin94** [comment]
Hi, I have addied these 3 papers.
