### ISSUE TITLE
Request to Add Paper

### ISSUE THREAD

**Issue by Francis0625** [zhaoxin94/awesome-domain-adaptation#124]
Hi：
Thanks for your contributions. We now have a SOTA MSDA paper that was published in TPAMI:
[[Graphical Modeling for Multi-Source Domain Adaptation]](https://ieeexplore.ieee.org/abstract/document/9767755) [[pytorch]](https://github.com/Francis0625/Graphical-Modeling-for-Multi-Source-Domain-Adaptation). This paper is the extension of our ECCV2020 paper, Learning to Combine: Knowledge Aggregation for Multi-Source Domain Adaptation.

We wish the work could be added to MSDA.
Thanks very much!

**Comment by zhaoxin94** [comment]
Very impressive work! I have added it to the list!
