### ISSUE TITLE
Request to add our ECCV22 paper

### ISSUE THREAD

**Issue by X-Lai** [zhaoxin94/awesome-domain-adaptation#125]
Thank you very much for maintaining this excellent repo.

Would you mind adding our ECCV 2022 paper "DecoupleNet: Decoupled Network for Domain Adaptive Semantic Segmentation"?
The paper link is `https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136930362.pdf`
The arXiv link is `https://arxiv.org/pdf/2207.09988.pdf`
The Code link is `https://github.com/dvlab-research/DecoupleNet`

Our work aims to solve the UDA Semantic Segmentation problem and achieves strong performance. We also propose a method based on self-training to further boost performance. Moreover, it can generalize well on the UDA classification task.

So I think it should to assigned to both the UDA Semantic Segmentation and Self-training-based categories.

Thank you very much!

**Comment by zhaoxin94** [comment]
Very impressive work! I have added it to the list!
