### ISSUE TITLE
Request for adding a new paper

### ISSUE THREAD

**Issue by Wang-Xiaodong1899** [zhaoxin94/awesome-domain-adaptation#130]
Hi Xin,
Thanks for your effort to this repo. We now have a new ACCV2022 paper for **Unsupervised DA**.
You can put this paper in **Unsupervised DA - Other methods** category.

Paper link: https://openaccess.thecvf.com/content/ACCV2022/html/Wang_Revisiting_Unsupervised_Domain_Adaptation_Models_a_Smoothness_Perspective_ACCV_2022_paper.html

Code link: (Pytorch)
https://github.com/Wang-Xiaodong1899/LeCo_UDA

Thanks very much!
Xiaodong

**Comment by zhaoxin94** [comment]
Very impressive work! I have added it to the list.
