### ISSUE TITLE
Request to add our AISTATS 2023 paper

### ISSUE THREAD

**Issue by VietHoang1512** [zhaoxin94/awesome-domain-adaptation#133]
Hi Xin,

Thanks for your effort to maintain this repository! 

Recently, we have a new paper for unsupervised domain adaptation [Global-Local Regularization Via Distributional Robustness](https://arxiv.org/abs/2203.00553) that has been accepted at the International Conference on Artificial Intelligence and Statistics (AISTATS 2023). Official release source code (Pytorch) could be found [here](https://github.com/VietHoang1512/GLOT/).

We think it might be suitable for Optimal Transport-based DA or Domain generalization.

Thanks in advance and best regards,
Hoang Phan

**Comment by zhaoxin94** [comment]
Very impressive and solid work! I have added your work into the list.
