### ISSUE TITLE
New ADA paper

### ISSUE THREAD

**Issue by sharat29ag** [zhaoxin94/awesome-domain-adaptation#136]
Hi, our group published the new ADA paper, "Reducing Annotation Effort by Identifying and Labeling Contextually Diverse.
Classes for Semantic Segmentation Under Domain Shift" WACV23. 
https://openaccess.thecvf.com/content/WACV2023/papers/Agarwal_Reducing_Annotation_Effort_by_Identifying_and_Labeling_Contextually_Diverse_Classes_WACV_2023_paper.pdf

**Comment by zhaoxin94** [comment]
I have added your paper to the list
