### ISSUE TITLE
New DA segmentation paper

### ISSUE THREAD

**Issue by BinhuiXie** [zhaoxin94/awesome-domain-adaptation#137]
Hi, @zhaoxin94, thx for sharing. Could you please add our new TPAMI 2023 paper on `Domain Adaptive Semantic Segmentation`: SePiCo: Semantic-Guided Pixel Contrast for Domain Adaptive Semantic Segmentation, the link is https://ieeexplore.ieee.org/document/10018569

with arxiv version:
https://arxiv.org/abs/2204.08808

and source code:
https://github.com/BIT-DA/SePiCo

Thank you very much!

**Comment by BinhuiXie** [comment]
Hi, @zhaoxin94, thanks for sharing this collection of papers. Also, could you please add two new papers about `Active DA`.

[AAAI2022] Active Learning for Domain Adaptation: An Energy-based Approach, the link is https://ojs.aaai.org/index.php/AAAI/article/view/20850
with arXiv version:
https://arxiv.org/abs/2112.01406

and source code:
https://github.com/BIT-DA/EADA

[CVPR2022 oral] Towards Fewer Annotations: Active Learning via Region Impurity and Prediction Uncertainty for Domain Adaptive Semantic Segmentation, the link is https://openaccess.thecvf.com/content/CVPR2022/papers/Xie_Towards_Fewer_Annotations_Active_Learning_via_Region_Impurity_and_Prediction_CVPR_2022_paper.pdf

with arxiv version:
https://arxiv.org/abs/2111.12940

and source code:
https://github.com/BIT-DA/RIPU

Thank you very much!

**Comment by zhaoxin94** [comment]
Sorry for the late reply. Very impressive and interesting work. I have added all three papers to the list.
