### ISSUE TITLE
Request to add multi-source DA paper for 3D object detection

### ISSUE THREAD

**Issue by darrenjkt** [zhaoxin94/awesome-domain-adaptation#149]
Hi,

Thanks for maintaining this repository. I have taken lots of inspiration from the papers you've collated!

I was wondering if you could add our work on multi-source DA that achieves SOTA in UDA for 3D object detection. We are the first approach in UDA for 3D object detection to leverage multiple pre-trained detectors and is able to generalize to lidars of any point cloud density. Our work shows significant improvements over state of the art. 

Title: MS3D++: Ensemble of Experts for Multi-Source Unsupervised Domain Adaptation in 3D Object Detection
Paper link: https://arxiv.org/abs/2308.05988
Code: https://github.com/darrenjkt/ms3d

**Comment by zhaoxin94** [comment]
Very interesting and impressive work! I have added the paper to the list.
