### ISSUE TITLE
add new paper request

### ISSUE THREAD

**Issue by chenchao666** [zhaoxin94/awesome-domain-adaptation#17]
Hi,

would you please add our new paper  HoMM: Higher-order Moment Matching for Unsupervised Domain Adaptation which is accepted in AAAI-2020.

btw, our method is a Distance-based Methods

official codes are avalible at https://github.com/chenchao666/HoMM-Master

Thanks,
chao

**Comment by zhaoxin94** [comment]
Hi, Chao

Your work is very impressive and interesting. I have added your paper in the latest update.
