### ISSUE TITLE
add code repo for some papers

### ISSUE THREAD

**Issue by AshleyQTDS** [zhaoxin94/awesome-domain-adaptation#25]
Hi,  this project is a nice job for newbee.

There exist some code repo that is missing in this project.

Diversify and Match: A Domain Adaptive Representation Learning Paradigm for Object Detection; Code at https://github.com/TKKim93/DivMatch

Adapting Object Detectors via Selective Cross-Domain Alignment; Code at https://github.com/xinge008/SCDA

**Comment by zhaoxin94** [comment]
Thanks!
