### ISSUE TITLE
Please add a new Distance-based method 

### ISSUE THREAD

**Issue by BinhuiXie** [zhaoxin94/awesome-domain-adaptation#29]
Hello, could you please add our new paper "Domain Conditioned Adaptation Network" that is accepted in AAAI2020

Domain Conditioned Adaptation Network [AAAI2020](https://arxiv.org/abs/2005.06717) [Pytorch](https://github.com/BIT-DA/DCAN)

Many thanks,
Xie

**Comment by zhaoxin94** [comment]
ok, very good work! I'll add it soon.
