### ISSUE TITLE
Could you please label `ECCV2020` to our paper.

### ISSUE THREAD

**Issue by AtsushiHashimoto** [zhaoxin94/awesome-domain-adaptation#36]
Hi. Thank you for your great efforts to maintain such an unbelievable exhaustive list for domain adaptation research.

Our paper, "Partially-Shared Variational Auto-encoders for Unsupervised Domain Adaptation with Target Shift", is currently listed as an arXiv paper, but it appeared in ECCV2020.
 https://www.ecva.net/papers/eccv_2020/papers_ECCV/html/2472_ECCV_2020_paper.php

We are really happy if you could update the list.
Thank you very much again.

**Comment by AtsushiHashimoto** [comment]
I forgot to provide the link to code.

https://github.com/iiyama-lab/PS-VAEs

Thank you very much for your attention.

**Comment by zhaoxin94** [comment]
OK! Your work is very interesting and impreesive!
