### ISSUE TITLE
Request for enlisting recent open-set DA journal article

### ISSUE THREAD

**Issue by tasfia** [zhaoxin94/awesome-domain-adaptation#46]
Hi Xin,

The repository is very impressive. Can you please add my IEEE Transactions on Multimedia article on open-set DA in your repository? 

Title: Adversarial Network with Multiple Classifiers for Open Set Domain Adaptation 
Authors: Tasfia Shermin, Guojun Lu, Shyh Wei Teng, Manzur Murshed, Ferdous Sohel
Publisher: IEEE TMM
Year: 2020
Code: https://github.com/tasfia/DAMC

Regards,
Tasfia

**Comment by zhaoxin94** [comment]
Hi, 

Your work is really interesting and impressive, and I have added it in this repo.
