### ISSUE TITLE
Please add a new One-shot UDA method.

### ISSUE THREAD

**Issue by RoyalVane** [zhaoxin94/awesome-domain-adaptation#50]
Hi Xin,

Thanks for your excellent work! The repository is very impressive and helpful! Could you please add Our NeurIPS2020 paper on One-shot UDA ( also can be regarded as an Unsupervised Domain-adaptive Semantic Segmentation ) in your repository?

Title: Adversarial Style Mining for One-shot Unsupervised Domain Adaptation
Authors: Yawei Luo, Ping Liu, Tao Guan, Junqing Yu, Yi Yang
Publisher: NeurIPS
Year: 2020
Code: https://github.com/RoyalVane/ASM

Best Regards,
Yawei

**Comment by zhaoxin94** [comment]
Hi Yawei,

Your work is really impressive and interesting.

I have added the paper into the list.

Best Regards,
Xin

**Comment by RoyalVane** [comment]
Thank you very much! I will close this issue then. Best wishes!
