### ISSUE TITLE
Could you add this paper?

### ISSUE THREAD

**Issue by GiovanniPasq** [zhaoxin94/awesome-domain-adaptation#56]
Hi, thank you for your amazing work. Could you add this paper to the repo? 
Paper is accepted to Image and Vision Computing journal.
Title: An Unsupervised Domain Adaptation Scheme for Single-Stage Artwork Recognition in Cultural Sites
Paper: https://arxiv.org/abs/2008.01882v3
Dataset: https://iplab.dmi.unict.it/EGO-CH-OBJ-UDA/
Code: https://github.com/fpv-iplab/DA-RetinaNet

Thank you :D

**Comment by zhaoxin94** [comment]
Hi, your work is really interesting! I have added it to the repo.
