### ISSUE TITLE
Please add a new UDA paper on ECCV-2020

### ISSUE THREAD

**Issue by Marsrocky** [zhaoxin94/awesome-domain-adaptation#62]
Hi @zhaoxin94 
We have a new UDA paper on ECCV-2020. The paper proposes a simple yet effective adversarial scheme to improve the original DANN (RevGrad) for domain adaptation.
Could you please help add it in this repo?

Name: Mind the Discriminability: Asymmetric Adversarial Domain Adaptation
Url: https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123690579.pdf

**Comment by zhaoxin94** [comment]
Sure! I have added it.

**Comment by jizefeng0810** [comment]
> Hi @zhaoxin94
> We have a new UDA paper on ECCV-2020. The paper proposes a simple yet effective adversarial scheme to improve the original DANN (RevGrad) for domain adaptation.
> Could you please help add it in this repo?
> 
> Name: Mind the Discriminability: Asymmetric Adversarial Domain Adaptation
> Url: https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123690579.pdf

Could you share the code of this paper? Thank you.

**Comment by zhaoxin94** [comment]
Sorry, I don't have the code of this paper. Maybe you can ask the original author for help.
________________________________
发件人: jizefeng0810 ***@***.***>
发送时间: 2021年4月15日 9:55
收件人: zhaoxin94/awesome-domain-adaptation ***@***.***>
抄送: Xin Zhao ***@***.***>; Mention ***@***.***>
主题: Re: [zhaoxin94/awesome-domain-adaptation] Please add a new UDA paper on ECCV-2020 (#62)


Hi @zhaoxin94<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzhaoxin94&data=04%7C01%7C%7C51a79ac4eb0644c39a6808d8ffb197f6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540485505784890%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xoJspGYrUR0oANLgOXMLsu1LI437l1s58WksoxJt6cw%3D&reserved=0>
We have a new UDA paper on ECCV-2020. The paper proposes a simple yet effective adversarial scheme to improve the original DANN (RevGrad) for domain adaptation.
Could you please help add it in this repo?

Name: Mind the Discriminability: Asymmetric Adversarial Domain Adaptation
Url: https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123690579.pdf<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ecva.net%2Fpapers%2Feccv_2020%2Fpapers_ECCV%2Fpapers%2F123690579.pdf&data=04%7C01%7C%7C51a79ac4eb0644c39a6808d8ffb197f6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540485505794894%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gmx7w2u0fLTdWnoTn5WXy67cse42BTNBnkosvP%2FE9ZA%3D&reserved=0>

Could you share the code of this paper? Thank you.

―

**Comment by adricarda** [comment]
I would be interested in the code as well. Is it possible to make it publicly available?

**Comment by Marsrocky** [comment]
Sorry for the delay due to other affairs. We will release the code in July.

**Comment by adricarda** [comment]
Thank you! it would be greatly appreciated.
