### ISSUE TITLE
Request to add new papers

### ISSUE THREAD

**Issue by hou-yz** [zhaoxin94/awesome-domain-adaptation#69]
Hi, thank you for organizing such a great repo. 
I would like to suggest our CVPR 2021 work to this collection.

### Visualizing Adapted Knowledge in Domain Transfer
arxiv: https://arxiv.org/abs/2104.10602
code: https://github.com/hou-yz/DA_visualization
section: Explainable (new); Image-to-Image Translation; Source-Free Domain Adaptation

This is the first attempt at explaining and visualizing the transferred knowledge during domain adaptation. We believe it would make a fine addition to a new Explainable section in the collection. In addition, it can also be deemed as a new approach under the Image-to-Image Translation section, and also helps to improve Source-Free Domain Adaptation performance.

Thank you for your effort!

**Comment by zhaoxin94** [comment]
Very intering work! I have added it into this repo.
