### ISSUE TITLE
Request to add our paper on Domain Generalisation

### ISSUE THREAD

**Issue by prinshul** [zhaoxin94/awesome-domain-adaptation#70]
Thank you for your huge efforts in maintaining such a useful repository.

Can you pease add our CVPR 2021 Oral paper on Domain Generalisation:
Domain Generalization via Inference-time Label-Preserving Target Projections

https://arxiv.org/abs/2103.01134

**Comment by zhaoxin94** [comment]
Sure!

**Comment by prinshul** [comment]
> Sure! Very impressive work!

Thank you.

**Comment by Anirudh257** [comment]
@prinshul Awesome stuff. Can you share the code for it?

**Comment by prinshul** [comment]
> @prinshul Awesome stuff. Can you share the code for it?

https://github.com/VSumanth99/InferenceTimeDG
