### ISSUE TITLE
Request to add our paper on Partial Domain Adaptation

### ISSUE THREAD

**Issue by lwpyh** [zhaoxin94/awesome-domain-adaptation#72]
Hi, I just found this repository，that's awesome ! Could you please add one early work Multi-Weight Partial Domain Adaptation(BMVC2019)(https://bmvc2019.org/wp-content/uploads/papers/0406-paper.pdf) to the partial DA part? Thank you~

**Comment by prinshul** [comment]
Please add following two papers to your awesome repository:
1. https://link.springer.com/chapter/10.1007/978-3-030-58539-6_25   (**ECCV 2020 Spotlight**)
Title: Unsupervised Domain Adaptation for Semantic Segmentation of NIR Images through Generative Latent Search
Code: https://github.com/ambekarsameer96/GLSS

2. https://ieeexplore.ieee.org/document/9139471
Title: Target-Independent Domain Adaptation for WBC Classification using Generative Latent Search  (**IEEE TMI 2020**)
Code: https://github.com/prinshul/WBC-Classification-UDA

Thank you.

**Comment by zhaoxin94** [comment]
Very interesting work! I have added it to the list.
