### ISSUE TITLE
Request to add an ICML 2021 paper

### ISSUE THREAD

**Issue by kilianFatras** [zhaoxin94/awesome-domain-adaptation#75]
Hello @zhaoxin94,

Thanks for the great DA paper list. Could you add the ICML 2021 paper : "Unbalanced minibatch Optimal Transport; applications to Domain Adaptation" to the list please ? It is an optimal transport method which was on both DA and partial DA.

The link to the paper is https://arxiv.org/abs/2103.03606 and to the code is https://github.com/kilianFatras/JUMBOT

Thank you very much.

**Comment by zhaoxin94** [comment]
Very impressive work! I have added it to the list.
