### ISSUE TITLE
Request to add new papers

### ISSUE THREAD

**Issue by tuanrpt** [zhaoxin94/awesome-domain-adaptation#81]
Thank you for your awesome repository for the researcher's references.
I would like to suggest some new papers here.

Optimal Transport for single UDA:
- TIDOT: A Teacher Imitation Learning Approach for Domain Adaptation with Optimal Transport [IJCAI 2021]
- LAMDA: Label Matching Deep Domain Adaptation [ICML 2021]

Optimal Transport for Multi-source DA:
- MOST: Multi-Source Domain Adaptation via Optimal Transport for Student-Teacher Learning [UAI 2021]

Multi-source DA:
- STEM: An approach to Multi-source Domain Adaptation with Guarantees [ICCV 2021]

Many thanks for your effort!

**Comment by zhaoxin94** [comment]
I have added these new papers.

Thanks!
