### ISSUE TITLE
Request for adding the ICRA 2022 paper

### ISSUE THREAD

**Issue by littleaich** [zhaoxin94/awesome-domain-adaptation#97]
Thanks for this awesome repo. Please add the following ICRA 2022 paper on UDA:

Unsupervised Domain Adaptation in LiDAR Semantic Segmentation with Self-Supervision and Gated Adapters, ICRA 2022 (accepted).
arxiv: https://arxiv.org/abs/2107.09783

**Comment by zhaoxin94** [comment]
Very interesting and attractive paper! I have added it into the list.
